# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       quilt
Summary:    Scripts for working with series of patches
Version:    0.48
Release:    1
Group:      Development/Tools
License:    GPLv2
URL:        http://savannah.nongnu.org/projects/quilt
Source0:    http://savannah.nongnu.org/download/quilt/quilt-%{version}.tar.gz
Source100:  quilt.yaml
Requires:   coreutils
Requires:   diffutils
Requires:   gzip
Requires:   bzip2
Requires:   sed
Requires:   gawk
Requires:   diffstat
Requires:   util-linux
Requires:   tar
Requires:   rpm-build
BuildRequires:  gettext
BuildRequires:  gawk
BuildRequires:  util-linux

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
These scripts allow one to manage a series of patches by keeping track of the
changes each patch makes. Patches can be applied, un-applied, refreshed, etc.

The scripts are heavily based on Andrew Morton's patch scripts found at
http://www.zip.com.au/~akpm/linux/patches/




%prep
%setup -q -n %{name}-%{version}
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --with-mta=%{_sbindir}/sendmail \
    --with-diffstat=%{_bindir}/diffstat

# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
export BUILD_ROOT=%{buildroot}
# << install pre
%make_install

# >> install post
mv $RPM_BUILD_ROOT/%{_docdir}/%{name}-%{version}/* .
rm -rf $RPM_BUILD_ROOT/%{_docdir}
# << install post
%find_lang quilt

%clean
rm -rf %{buildroot}






%files -f quilt.lang
%defattr(-,root,root,-)
# >> files
%doc README README.MAIL quilt.pdf
%doc AUTHORS COPYING TODO
%{_bindir}/guards
%{_bindir}/quilt
%{_datadir}/quilt/
%{_datadir}/emacs/site-lisp/quilt.el
%{_libdir}/quilt/
%{_sysconfdir}/bash_completion.d
%config %{_sysconfdir}/quilt.quiltrc
%{_mandir}/man1/*
# << files


